### ISSUE TITLE
Error while using gulp-coverage

### ISSUE THREAD

**Issue by DennisAhaus** [dylanb/instrumentjs#1]
When using gulp-coverage i got this error:

``` js

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: Line 8: Unexpected reserved word
    at throwError (/home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:1470:21)
    at throwUnexpected (/home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:1518:17)
    at parsePrimaryExpression (/home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:1832:16)
    at /home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:3577:38
    at trackLeftHandSideExpressionAllowCall (/home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:3483:61)
    at parsePostfixExpression (/home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:1938:20)
    at /home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:3577:38
    at parseUnaryExpression (/home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:2001:16)
    at /home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:3577:38
    at parseBinaryExpression (/home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:2103:16)
    at /home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:3577:38
    at parseConditionalExpression (/home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:2144:16)
    at /home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:3577:38
    at parseAssignmentExpression (/home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:2167:16)
    at /home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:3577:38
    at parseExpression (/home/vagrant/Desktop/dev/node-express-crud-router/node_modules/gulp-coverage/node_modules/instrumentjs/esprima.js:2191:20)
```

My gulpfile looks like:

``` js
(function() {
  'use strict';
  var gulp = require('gulp');
  var mocha = require('gulp-mocha');
  var cover = require('gulp-coverage');

  gulp.task('test', function() {

    return gulp
      .src('test/suite.js', {
        read: false
      })
      .pipe(cover.instrument({
        pattern: ['lib/**/*.js']
      }))
      // gulp-mocha needs filepaths so you can't have any plugins before it
      .pipe(mocha({
        reporter: 'spec'
      }))
      .pipe(cover.gather())
      .pipe(cover.format())
      .pipe(gulp.dest('reports/coverage'));
  });

}());

```

What iam doing wrong?

**Comment by dylanb** [comment]
@DennisAhaus can you share the piece of the code that is causing this? Your gulpfile looks fine.

Are you using ES6?

**Comment by DennisAhaus** [comment]
Hi @dylanb ,

yes, i am using ES6. The code is here in github: https://github.com/DennisAhaus/node-express-crud-router

**Comment by dylanb** [comment]
This version does not support ES6. I have been working on an ES6 version but that is currently a long way from completion.

**Comment by DennisAhaus** [comment]
Ah ok, thx for that. I will wait until es6 works
